---
# tasks file for roles/docker-telegraf
- name: Create paths
  file:
    path: "/docker/containers/telegraf/"
    state: directory
    mode: 0775

- name: Copy telegraf config file
  template:
    src: telegraf.conf.j2
    dest: /docker/containers/telegraf/telegraf.conf
    mode: 0644
  tags: telegraf, config

- name: Start telegraf container
  docker_container:
    name: telegraf
    image: telegraf
    state: started
    restart: true
    restart_policy: unless-stopped
    exposed_ports:
      - 8125
      - 8092
      - 8094
    published_ports:
      - 8125:8125
      - 8092:8092
      - 8094:8094
    volumes:
      - /docker/containers/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env:
