- name: Install useful commandline programs
  yum:
      name: "{{ item }}"
      state: present
  with_items:
    - firewalld
    - epel-release
    - net-snmp
    - net-snmp-libs
    - net-snmp-utils

- name: Copy snmp config
  copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: 0600
  notify: restart snmpd

- name: Start SNMPD
  systemd:
      name: snmpd
      state: started
      enabled: yes
      daemon_reload: yes
  tags: snmpd, service

- name: install some useful nagios plugins
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{nagiosPlugins}}"

- name: Start nrpe
  systemd:
      name: nagios-nrpe-service
      state: started
      enabled: yes
      daemon_reload: yes
  tags: nagios, service

- name: Start the firewalld service
  systemd:
      name: firewalld
      state: started
      enabled: yes
      daemon_reload: yes
  tags: service

- name: Firewalld Allow NRPE
  firewalld:
    port: 5666/tcp
    permanent: true
    state: enabled
  notify: restart firewalld

- name: Firewalld Allow snmp
  firewalld:
    port: 161/udp
    permanent: true
    state: enabled
  notify: restart firewalld
