---
- hosts: webservers
  sudo: yes

  vars_files:
    - ../vars.yml
    - vars.yml

  pre_tasks:

  roles:
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.security, tags: ['security'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.git, tags: ['git'] }
    - { role: geerlingguy.nfs, tags: ['nfs'] }
    - { role: ../roles/leds, tags: ['leds'] }

  tasks:
    - include: tasks/extras.yml
    - include: tasks/config.yml
    - include: tasks/nfs.yml
    - include: tasks/led-monitor.yml
