- name: Install useful commandline programs
  yum: name={{ item }} state=present
  with_items:
    - nano
    - wget
    - yum-cron
    - git

- name: Start Yum Cron
  service: name=yum-cron state=started enabled=yes
  tags: yum, service

- name: Start nrpe
  service: name=nrpe state=started enabled=yes
  tags: nagios, service

- name: Install python bindings for SE Linux
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python

- name: install some useful nagios plugins
  yum: name={{ item }} state=present
  with_items:
    - nagios-nrpe
    - nagios-plugins-swap
    - nagios-plugins-users
    - nagios-plugins-procs
    - nagios-plugins-load
    - nagios-plugins-disk

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp, service

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp, service
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
