- name: Copy Docker Repo
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo
    owner: root
    group: root
    mode: 0644

- name: Install Docker
  yum: name={{ item }} state=present
  with_items:
    - docker-engine

- name: Start Docker
  service: name=yum-cron state=started enabled=yes
  tags: yum, service
