- name: Copy Docker Repo
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo
    owner: root
    group: root
    mode: 0644

- name: Install Docker
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-engine
    - python-pip

- name: Start Docker
  service:
      name: yum-cron
      state: started
      enabled: yes
      daemon_reload: yes
  tags: yum, service

- name: Ensure that Docker Group exsists
  group:
    name: docker
    state: present

- name: Add User to Docker Group
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    group: "docker"
    append: yes
  with_items:
    - "{{ docker_users }}"

- name: Open Ports for Docker Containers
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ docker_ports }}"
  notify: Restart firewalld
