---
- name: Copy vhost configuration into place.
  template:
    src: ../templates/drupal.conf.j2
    dest: /etc/nginx/sites-enabled/drupal.conf
    mode: 0644
  notify: restart nginx

- name: Ensure php5-fpm www pool configuration directory exists.
  file:
    path: /etc/php5/fpm/pool.d
    state: directory

- name: Copy php5-fpm www pool configuration into place.
  template:
    src: ../templates/www.conf.j2
    dest: /etc/php5/fpm/pool.d/www.conf
    mode: 0644
  notify: restart php-fpm

- name: Ensure pi user is in www-data group.
  user:
    name: pi
    groups: www-data
    append: yes
